name: atari_gpt
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2024.7.2=hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.14=h80987f9_0
  - pip=24.0=py39hca03da5_0
  - python=3.9.19=hb885b13_1
  - readline=8.2=h1a28f6b_0
  - setuptools=72.1.0=py39hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py39hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - ale-py==0.8.1
      - annotated-types==0.6.0
      - anthropic==0.25.7
      - anyio==4.3.0
      - autorom==0.4.2
      - autorom-accept-rom-license==0.6.1
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==4.4.2
      - distro==1.9.0
      - exceptiongroup==1.2.1
      - farama-notifications==0.0.4
      - filelock==3.14.0
      - fonttools==4.53.1
      - fsspec==2024.3.1
      - google-ai-generativelanguage==0.6.2
      - google-api-core==2.19.0
      - google-api-python-client==2.127.0
      - google-auth==2.29.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.5.2
      - googleapis-common-protos==1.63.0
      - groq==0.5.0
      - grpcio==1.63.0
      - grpcio-status==1.62.2
      - gymnasium==0.29.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - idna==3.7
      - imageio==2.34.2
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - kiwisolver==1.4.5
      - matplotlib==3.9.1.post1
      - moviepy==1.0.3
      - numpy==1.26.4
      - openai==1.25.0
      - opencv-python==4.9.0.80
      - packaging==24.0
      - pillow==10.4.0
      - proglog==0.1.10
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygame==2.6.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - requests==2.31.0
      - rsa==4.9
      - shimmy==0.2.1
      - six==1.16.0
      - sniffio==1.3.1
      - tokenizers==0.19.1
      - tqdm==4.66.2
      - typing-extensions==4.11.0
      - uritemplate==4.1.1
      - urllib3==2.2.1
      - zipp==3.19.2
